travis:
  secure:
    BINSTAR_TOKEN: J7/RQvuhOZetdODs42sVYZxEoQfYQP2HEEyfo3f4i7H0PR1/VVsc9MQjhv4Es8rlXiG4zaat2rJ578xMAKTtZo5U4NdFQorUUXx/dB4ZiGfaA0VdTH+dCg6w+yASwAvNUz5FlVdVRt6ZnXVKrAdtcyyV3vqq0xkHIEOPgcaTXAJZ9swyb1TDHkJ/I9/ZbD5PP2ebmKIVXr2/vBliBeGapLYDAsO9mqscWJV1Emm8SOrhGEKT71CRtiOz872AtJKw56yAVfwnhMTsvhmRlfZsu+Qb5qIMjH0o5yyWhBMe4GINXYDrscKc/2HA9j4zu+w9HO+1rB1qI9Z6PXdUsV+WulurvZ1guQxZDCnbRK4S/761VQZISDAa1VHnn8LC28n5csWQbI0jo8BG9ra/ninGCyLtDsAde9zjZ3udKkOCnUshxJlG/IVQM7mdqtuOmzqOyM1v3udzGNVc6TO0uyhPiUThSqIeC9DQett8DVhgUgFgyGoV9ctWJQvZPfcQFTFW2DMZypYf72WmCynJARBSHGs4+WEXCg3XN3kMqZE7CUh0HDaJifmEhyN/uBcJpOucgOHcAdxwwyse8ulckkP2uu0eftHbF5aZuRG0fA/QEhn0vKyv0mQR1z+kM+5wYoVSlYuN2NG0tENiHmscG1QYN8GAeaY8IylF8p8XdtyFs2w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
